version: '3.8'

services:
  nginx:
    depends_on:
      - back
      - front
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3051:80"

  back:
    build:
      dockerfile: Dockerfile
      context: "./back"
    volumes:
      - /app/node_modules
      - ./back:/app
    environment:
      JWT_KEY: "not secret"
      DB_PATH: "./assets/db"

  front:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./front
    volumes:
      - /app/node_modules
      - ./front:/app
    environment:
      DANGEROUSLY_DISABLE_HOST_CHECK: true
      REACT_APP_LOGO_DIR: "src/assets/images"
      REACT_APP_LOGO: "src/assets/images/bibliotheca.png"